name: Post GitHub Update

on:
  release:
    types: [published]

jobs:
  post:
    name: Post To Discord
    runs-on: ubuntu-latest
    steps:
      - name: Run Python
        id: runit
        shell: bash
        run: |
          python3 code/.github/sendupdate.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
